# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime

- task: DotNetCoreCLI@2
  displayName: 'Restore website dependencies'
  inputs:
    command: 'restore'
    projects: '**/webui.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Restore integration test dependencies'
  inputs:
    command: 'restore'
    projects: '**/webui.IntegrationTest.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build website - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/webui.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build integration tests - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/webui.IntegrationTest.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Run integration tests'
  inputs:
    command: 'test'
    projects: '**/webui.IntegrationTest.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Publish webiste artifact'
  inputs:
    command: 'publish'
    projects: '**/webui.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/web'
    zipAfterPublish: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/web'
    ArtifactName: 'todo-web'
    publishLocation: 'Container'
